### ISSUE TITLE
Emacs isn't responding, sequencep error when specified jvm parameter

### ISSUE THREAD

**Issue by vsuharnikov** [ag91/scala-cli-repl#2]
Hello! Thanks for your module, very appreciated your work.

1. I tried to use an `org-babel` integration and Emacs wasn't responding. All I see is the message "Waiting for scala-cli to start" with a lot of attempts. The solution was simple:
    ```
    (setq scala-cli-repl-program (executable-find "scala-cli")) ;; HACK for macOS + nix (?)
    ```
2. There is a missed useful scala-cli parameter - `:jvm`. To support this, add it as mentioned in README:
   ```
    (setq ob-scala-cli-supported-params '(:scala-version :dep :jvm))
   ```
   But you can get an error, e.g.:
   ```
   #+begin_src scala :scala-version 2.13.11 :jvm 11
   println(s"test1 ${1+1}")
   #+end_src
   ```
   > format: Wrong type argument: sequencep, 11
   
   To solve it, change the `jvm` argument type to the string: `:jvm "11"`

**Comment by ag91** [comment]
hey thanks for the nice words and the in depth description of the issue. It made my life easier in trying to address it: could you confirm the latest commit works fine with you? 
I made it so you can add the :jvm option without wrapping it in a string ;)

**Comment by vsuharnikov** [comment]
Now it works! 🎉
