### ISSUE TITLE
Wrong number of arguments (when executing the code-block?)

### ISSUE THREAD

**Issue by bphenriques** [ag91/scala-cli-repl#6]
Hello,

Thank you for creating an alternative to [`ob-ammonite`](https://github.com/zwild/ob-ammonite) but compatible with scala-cli 🙇  I was looking forward for this!

I am somewhat a Emacs newbie and I am using doom-emacs. I was used to `Ctrl-C Ctrl-C` to execute code-blocks and see the results back. I managed to setup the plugin but I get a "Wrong number of arguments" error right after I execute the code-block:

<img width="1477" alt="image" src="https://github.com/ag91/scala-cli-repl/assets/4727729/7c983cb8-c06d-446f-be89-69ab79acfe66">

To be honest, I am still getting acquainted with the emacs setup after a short break from using it. What is the best approach to debug? It is very likely a bug in my setup, although it is mostly vanilla Doom Emacs.

I am using Emacs 29.2, latest doom-emacs and the following config:
```elisp
;; under packages.el
(package! scala-cli-repl
  :recipe (:host github :repo "ag91/scala-cli-repl" :files ("*.el")) :pin "e19457e3a78674154959ad305a0ab7c3f87e6bab")

;; under config.el
(after! org-mode
  :config
    (add-to-list 'org-babel-load-languages '(scala-cli . t) '(scala .))
    (setq ob-scala-cli-default-params '(:scala-version "3.3.1" :jvm 21)))
``` 

Thank you in advance!

**Comment by ag91** [comment]
hey thanks for reporting, just to be sure: is this a typo in your report `    (add-to-list 'org-babel-load-languages '(scala-cli . t) '(scala .))` ? It should be `'(scala . t)`.
Maybe could you try the command `toggle-debug-on-error`? That should open a buffer with the error trace, which could help us in debugging this.

**Comment by bphenriques** [comment]
Nice catch 😓  but that wasn't it. Updated the config, re-synced doom emacs, restart the server and created a new emacs session.

Source:
```org
#+BEGIN_SRC scala
1+1
#+END_SRC
```

Output of the buffer with the error trace:
```
Debugger entered--Lisp error: (wrong-number-of-arguments #<subr s-split> 1)
  s-split("/repl.sc")
  ob-scala-cli--parse-response-3("/var/folders/jy/_wzmc9814v98mggwfhmn9gyw0000gn/T/ob-scala-cli/repl.sc" ":load /va\10\10var/folders/jy/_wzmc9814v98mggwfhmn9gyw0000gn/T/ob-scala-cli/repl.sc\15\15\nval res2: Int = 2\15\n~                                                                                                                                                                          \15 \15\15\15\nscala> ")
  org-babel-execute:scala("1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:session . "none") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export")))
  #<subr org-babel-execute-src-block>(nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)") nil nil)
  apply(#<subr org-babel-execute-src-block> (nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)")))
  (closure ((args nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)")) (orig . #<subr org-babel-execute-src-block>)) nil (apply orig args))()
  inheritenv-apply((closure ((args nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)")) (orig . #<subr org-babel-execute-src-block>)) nil (apply orig args)))
  (if envrc-mode (inheritenv-apply #'(lambda nil (apply orig args))) (apply orig args))
  envrc-propagate-environment(#<subr org-babel-execute-src-block> nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)"))
  apply(envrc-propagate-environment #<subr org-babel-execute-src-block> (nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)")))
  org-babel-execute-src-block(nil ("scala" "1+1" ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 1 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  command-execute(org-ctrl-c-ctrl-c)
```

Setup: using macos, emacs 29.1 installed using Nix ([link if useful](https://github.com/bphenriques/dotfiles/blob/master/home/config/emacs/doom/%2Bscala.el))

Edit: Scala Cli buffer seems healthy: 
<img width="696" alt="image" src="https://github.com/ag91/scala-cli-repl/assets/4727729/3fbcf3e2-8ca9-4e26-965e-9638b30fd735">


Edit2: expanded the error message as it had some ellipsis `...`

**Comment by bphenriques** [comment]
I see a `ob-scala-cli--parse-response-3("/var/folders/jy/_wzmc9814v98mggwfhmn9gyw0000gn/T/o..."`, let me see if I can see the content of the file it is trying to parse (assuming the argument should be a file)

**Comment by ag91** [comment]
curious, this works on my side:
```
(ob-scala-cli--parse-response-3 "/var/folders/jy/_wzmc9814v98mggwfhmn9gyw0000gn/T/ob-scala-cli/repl.sc" ":load /va\10\10var/folders/jy/_wzmc9814v98mggwfhmn9gyw0000gn/T/ob-scala-cli/repl.sc\15\15\nval res2: Int = 2\15\n~                                                                                                                                                                          \15 \15\15\15\nscala> ")
```
Can you try again with the latest commit? I have just removed an unexpected usage of dash.el, which surprised me and could be the source of your error.

**Comment by bphenriques** [comment]
It does work now 🥳  Thank you!
```
#+BEGIN_SRC scala
1+1
#+END_SRC

#+RESULTS:
: val res0: Int = 2
```

For curiosity, the `->>` is a dash.el command that should not be used as it is not declared explicitly as dependency (checked the commit)?

**Comment by ag91** [comment]
apologies for that, I didn't set up a proper CI yet and I missed that bit in an accepted PR.
Indeed, a package should declare dependencies as `(require ...)` at the beginning of the file, so that they can be pulled by your package manager (`use-package`).
`->>` is a dash.el operator that is also implemented in Emacs as `thread-last`, so I used that instead.
(It just lets you pipe/thread operations and injects the result of each as last input of the next form)

Thanks again for reporting this!
